apiVersion: v1
kind: Service

metadata:
  name: redis
  labels:
    name: redis-srv
    app: myApp


spec:
  type: LoadBalancer
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: myApp